set -g prefix C-q
unbind C-b

# prefix+\でペインを垂直分割する
bind \\ split-window -h

# prefix+-でペインを水平分割する
bind - split-window -v

# ウィンドウを切り替える
bind -n S-left previous-window
bind -n S-right next-window

# 256色モードを有効にする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# ステータスバーの色を設定する
set-option -g status-bg "colour238"

# status line の文字色を指定する。
set-option -g status-fg "colour255"

# ステータスラインの色を変更
setw -g status-style fg=colour255,bg=colour234

# status-leftを非表示にする
set -g status-left ""

# status-rightを非表示にする
set -g status-right ""

# window-statusを右寄せにする
set -g status-justify right

# windowのインデックスを1から始める
set -g base-index 1

# window-statusの見た目を変更
setw -g window-status-current-format '#[bg=colour2,fg=colour255] #I #W '
setw -g window-status-format '#[fg=colour242] #I #W '
setw -g window-status-current-format '#[bg=colour2,fg=colour255]#{?client_prefix,#[bg=colour3],} #I #W '

# vimキーバインド
setw -g mode-keys vi

# ペインのリサイズ（prefix + H/J/K/L）
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# マウス操作を有効にする
set-option -g mouse on

# prefix+r で設定のリロード
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
